# safelist
  before_install
   - mysql -e 'CREATE DATABASE sistemadb;'
   - mysql -u root -p sistemadb < sistemadb.sql
language: java
install: ant deps
sudo: true
script: ant test

services:
  - mysql
branches:
  only:
  - master
