# safelist
language: java
install: ant deps
sudo: true

services:
  - mysql
branches:
  only:
  - master

  before_install
   - mysql -e 'CREATE DATABASE sistemadb;'
   - mysql -u root -p sistemadb < sistemadb.sql
