# safelist
language: java
sudo: true
script: mvn clean verify

services:
  - mysql
branches:
  only:
  - master

  before_install
   - mysql -e 'CREATE DATABASE sistemadb;'
   - mysql -u root -p sistemadb < sistemadb.sql
